-- MySQL Script generated by MySQL Workbench
-- 09/29/18 20:19:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sec` DEFAULT CHARACTER SET utf8 ;
USE `sec` ;

-- -----------------------------------------------------
-- Table `sec`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `app` VARCHAR(45) NULL,
  `apm` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sec`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sec`.`Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Nivel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sec`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Horario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lunes` VARCHAR(45) NULL,
  `hora_lunes` VARCHAR(45) NULL,
  `martes` VARCHAR(45) NULL,
  `hora_martes` VARCHAR(45) NULL,
  `miercoles` VARCHAR(45) NULL,
  `hora_miercoles` VARCHAR(45) NULL,
  `jueves` VARCHAR(45) NULL,
  `hora_jueves` VARCHAR(45) NULL,
  `viernes` VARCHAR(45) NULL,
  `hora_viernes` VARCHAR(45) NULL,
  `sabado` VARCHAR(45) NULL,
  `hora_sabado` VARCHAR(45) NULL,
  `domingo` VARCHAR(45) NULL,
  `hora_domingo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sec`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Alumno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sec`.`Usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sec`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Profesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cvs` VARCHAR(90) NULL,
  `foto` VARCHAR(90) NULL,
  `idUsuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `idUsuario2`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sec`.`Usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sec`.`Usuario_Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Usuario_Nivel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  `idNivel` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  INDEX `idNivel_idx` (`idNivel` ASC),
  CONSTRAINT `idUsuario6`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sec`.`Usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idNivel6`
    FOREIGN KEY (`idNivel`)
    REFERENCES `sec`.`Nivel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sec`.`Evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Evaluacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `evaluacion` DOUBLE NULL,
  `idNivel` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario_idx` (`idNivel` ASC),
  CONSTRAINT `idUsuario4`
    FOREIGN KEY (`idNivel`)
    REFERENCES `sec`.`Usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sec`.`Materias_Interes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Materias_Interes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  `idMateria` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  INDEX `idMateria_idx` (`idMateria` ASC),
  CONSTRAINT `idUsuario5`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sec`.`Usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idMateria5`
    FOREIGN KEY (`idMateria`)
    REFERENCES `sec`.`Materia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sec`.`Clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Clase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `costo` DOUBLE NULL,
  `ocupado` VARCHAR(45) NULL,
  `idMateria` INT NULL,
  `idProfesor` INT NULL,
  `idNivel` INT NULL,
  `idHorario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idMateria_idx` (`idMateria` ASC),
  INDEX `idProfesor_idx` (`idProfesor` ASC),
  INDEX `idNivel_idx` (`idNivel` ASC),
  INDEX `idHorario_idx` (`idHorario` ASC),
  CONSTRAINT `idMateria2`
    FOREIGN KEY (`idMateria`)
    REFERENCES `sec`.`Materia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idProfesor2`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `sec`.`Profesor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idNivel2`
    FOREIGN KEY (`idNivel`)
    REFERENCES `sec`.`Nivel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idHorario2`
    FOREIGN KEY (`idHorario`)
    REFERENCES `sec`.`Horario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sec`.`Alumno_Clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sec`.`Alumno_Clase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idClase` INT NULL,
  `idAlumno` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idClase_idx` (`idClase` ASC),
  INDEX `idAlumno_idx` (`idAlumno` ASC),
  CONSTRAINT `idClase1`
    FOREIGN KEY (`idClase`)
    REFERENCES `sec`.`Clase` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idAlumno3`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `sec`.`Alumno` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
